### ISSUE TITLE
Stop plugin from adding class .widget to widgets ...

### ISSUE THREAD

**Issue by MennovanderKrift** [phpbits/widget-options#26]
The plugin adds the class .widget to all of my widgets, which is getting picked up by the theme and is applying additional CSS that I don’t need. How do I remove the class .widget from my widgets? Why is this even on by default? Because this might be confusing for people that don’t even notice the additional class.

**Comment by phpbits** [comment]
Hi,

Thank you very much for choosing Widget Options! Regarding your concern, adding .widget class should be default and required for WordPress standard templating. Since the theme you are using isn't following the standard, you have to edit the plugin file here : https://github.com/phpbits/widget-options/blob/master/includes/widgets/display.php and comment out line 325. I'll be adding option on the next release to avoid editing the file ;)  Let me know how it goes. Thanks!

Cheers,
Jeffrey

**Comment by phpbits** [comment]
Hello again @MennovanderKrift 

I've added an option under Settings > Widget Options and on **Classes & ID** card you'll get checkbox to disable .widget class addition. Please download the version fix here : https://github.com/phpbits/widget-options/tree/develop and let me know how it goes. Thanks!

Cheers,
Jeffrey
