### ISSUE TITLE
Removing sidebar from single posts

### ISSUE THREAD

**Issue by ghost** [phpbits/widget-options#27]
Please forgive me if my terminology is bad. I'm combining my web site and old blog on Wordpress.org using Photocrati. So far, so good, but I would like to have the sidebar only on the blog page and not on the single post pages. I activated Widget Options and got it to work, but... although it has removed the sidebar, I still have the space left on the right hand side. Can you help please?

**Comment by phpbits** [comment]
Hi,

Thank you very much for choosing Widget Options! Regarding your concern, there is no option to remove the empty sidebar automatically as of the moment. This is because of the template you are using, even if you hide/remove the sidebar the width of the content container will remain the same, not fullwidth. Thank you very much for your understanding. 

Cheers,
Jeffrey
